version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: hackathon2024
      POSTGRES_USER: bdh_user
      POSTGRES_DB: bdh_database
    ports:
      - "6789:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Override JDBC for local db service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bdh_database?preferQueryMode=simple&prepareThreshold=0&autosave=always
      SPRING_DATASOURCE_USERNAME: bdh_user
      SPRING_DATASOURCE_PASSWORD: hackathon2024
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:


